from __future__ import annotations

import base64
import copy
import hashlib
import json
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from helper.models import ArtifactClass, Candidate, Check, LifecycleAction, Operation, OperationKind, Ownership, Preimage, Receipt, RuntimeContext
from helper.ownership import load_ownership_catalog
from helper.paths import explicit_platform_config_root, root_relative_path

CLIENT = "pi"
VERSION = "1"
LAYOUT_VERSION = "pi-bounded-v1"
ACTIVE_PACKAGE = "npm:gentle-pi"
REGISTRY_SIGNATURE = "<!-- Auto-generated by gentle-pi extensions/skill-registry.ts. -->"
_ACTIVE_PACKAGE_RE = re.compile(r"^npm:gentle-pi(?:@[^\s]+)?$")


class _RealClock:
    def time(self) -> float:
        return time.monotonic()


class _RealSleeper:
    def sleep(self, seconds: float) -> None:
        time.sleep(seconds)


@dataclass(frozen=True)
class _ProcessState:
    block_registry: bool = False
    lifecycle_action: LifecycleAction | None = None
    evidence: tuple[dict[str, object], ...] = ()
    block_reason: str | None = None


class PiAdapter:
    client = CLIENT
    version = VERSION
    layout_version = LAYOUT_VERSION

    def __init__(
        self,
        catalog: Mapping[str, Any] | None = None,
        *,
        process_probe: object | None = None,
        clock: object | None = None,
        sleeper: object | None = None,
        quiet_interval: float = 0.0,
        poll_interval: float = 0.1,
    ) -> None:
        self.catalog = load_ownership_catalog() if catalog is None else catalog
        self.process_probe = process_probe
        self.clock = clock if clock is not None else _RealClock()
        self.sleeper = sleeper if sleeper is not None else _RealSleeper()
        self.quiet_interval = max(0.0, float(quiet_interval))
        self.poll_interval = max(0.001, float(poll_interval))

    def inventory(self, context: RuntimeContext) -> tuple[Candidate, ...]:
        candidates: list[Candidate] = []
        for settings_path in _settings_paths(context):
            if not settings_path.exists():
                continue
            if not settings_path.is_file():
                raise ValueError(f"pi_settings_invalid_layout:{settings_path.name}")
            settings = _load_settings(settings_path)
            active_packages = tuple(package for package in _settings_packages(settings) if _is_active_pi_package(package))
            if active_packages:
                candidates.append(_settings_candidate(settings_path, active_packages, context))
            candidates.extend(_preserved_package_candidates(settings_path.parent, context))

        cosmetic = context.profile.home / ".pi" / "gentle-ai"
        if cosmetic.is_dir() and not any(cosmetic.iterdir()):
            candidates.append(_cosmetic_candidate(cosmetic, context))

        process_state = self._process_state(context)
        registries: list[Candidate] = []
        for root in context.project_roots:
            target = root / ".atl" / "skill-registry.md"
            if not target.exists():
                continue
            registries.append(_registry_candidate(target, context, process_state))
        candidates.extend(_attach_lifecycle_to_first_registry(registries, process_state))

        return tuple(sorted(candidates, key=lambda candidate: (candidate.path, candidate.candidate_id)))

    def compile(self, candidate: Candidate, context: RuntimeContext) -> tuple[Operation, ...]:
        if candidate.ownership != Ownership.PROVEN or candidate.proposed_action == "report_only":
            return ()
        kind = candidate.details.get("kind")
        if kind == "settings_registration" and candidate.proposed_action == "write_file":
            return self._compile_settings(candidate)
        if kind == "generated_registry" and candidate.proposed_action == "delete_file":
            return self._compile_registry_delete(candidate, context)
        return ()

    def verify(self, receipt: Receipt, context: RuntimeContext) -> tuple[Check, ...]:
        self._verify_lifecycle_restart(receipt)
        for settings_path in _settings_paths(context):
            if not settings_path.exists():
                continue
            settings = _load_settings(settings_path)
            remaining = [package for package in _settings_packages(settings) if _is_active_pi_package(package)]
            if remaining:
                raise ValueError("verify_pi_package_registration_present")
            self._verify_preserved_package_sentinel(settings_path)

        for outcome in getattr(receipt, "operation_outcomes", ()):  # independent live checks, bounded by receipt targets when present
            if getattr(outcome, "status", "") != "completed":
                continue
            target = Path(str(getattr(outcome, "path", "")))
            try:
                kind = OperationKind(str(getattr(outcome, "kind", "")))
            except ValueError:
                continue
            if kind == OperationKind.DELETE_FILE and target.exists() and _is_authorized_registry_path(target, context):
                if _registry_is_proven(target):
                    raise ValueError("verify_pi_registry_regrew")
            if kind == OperationKind.WRITE_FILE and target.exists() and target in _settings_paths(context):
                _load_settings(target)

        self._verify_registries_quiet(context)
        return tuple(getattr(receipt, "checks", ()))

    def _compile_settings(self, candidate: Candidate) -> tuple[Operation, ...]:
        path = Path(candidate.path)
        before = _load_settings(path)
        after = copy.deepcopy(before)
        packages = _settings_packages(after)
        cleaned = [package for package in packages if not _is_active_pi_package(package)]
        if cleaned == packages:
            return ()
        after["packages"] = cleaned
        postimage = (json.dumps(after, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
        json.loads(postimage.decode("utf-8"))
        return (
            Operation(
                kind=OperationKind.WRITE_FILE,
                path=candidate.path,
                postimage_base64=base64.b64encode(postimage).decode("ascii"),
                postimage_sha256=_sha256(postimage),
                details={
                    "content_type": "application/json",
                    "operation": "disable_pi_package_registration",
                    "removed_packages": tuple(candidate.details.get("active_packages", ())),
                    "root_id": candidate.details.get("root_id"),
                    "relative_path": candidate.details.get("relative_path"),
                },
            ),
        )

    def _compile_registry_delete(self, candidate: Candidate, context: RuntimeContext) -> tuple[Operation, ...]:
        path = Path(candidate.path)
        if not _is_authorized_registry_path(path, context):
            return ()
        if not path.is_file() or not _registry_is_proven(path):
            return ()
        root_id, relative_path = root_relative_path(path, context)
        if relative_path != ".atl/skill-registry.md" or root_id == "home":
            return ()
        return (
            Operation(
                kind=OperationKind.DELETE_FILE,
                path=candidate.path,
                details={
                    "operation": "delete_generated_pi_skill_registry",
                    "root_id": root_id,
                    "relative_path": relative_path,
                },
            ),
        )

    def _process_state(self, context: RuntimeContext) -> _ProcessState:
        if self.process_probe is None or getattr(self.process_probe, "inspect_pi_processes", None) is None:
            return _ProcessState(
                block_registry=True,
                block_reason="process_probe_unavailable",
                evidence=({"kind": "process_probe_unavailable", "probe": "inspect_pi_processes"},),
            )
        sessions = _probe_pi_sessions(self.process_probe, context)
        affected = [session for session in sessions if _session_bool(session, "running") and _session_bool(session, "loaded_gentle_pi")]
        if not affected:
            return _ProcessState()
        evidence = tuple(_session_evidence(session) for session in affected)
        if len(affected) != 1:
            return _ProcessState(block_registry=True, block_reason="ambiguous_multiple_affected_sessions", evidence=evidence + ({"kind": "pi_process_state", "state": "ambiguous_multiple_affected_sessions"},))
        action = _session_lifecycle_action(affected[0], context)
        if action is None:
            return _ProcessState(block_registry=True, block_reason="missing_safe_restart_metadata", evidence=evidence + ({"kind": "pi_process_state", "state": "missing_safe_restart_metadata"},))
        return _ProcessState(lifecycle_action=action, evidence=evidence)

    def _verify_registries_quiet(self, context: RuntimeContext) -> None:
        deadline = self.clock.time() + self.quiet_interval  # type: ignore[attr-defined]
        while True:
            if _any_proven_registry(context):
                raise ValueError("verify_pi_registry_regrew")
            now = self.clock.time()  # type: ignore[attr-defined]
            if now >= deadline:
                return
            self.sleeper.sleep(min(self.poll_interval, deadline - now))  # type: ignore[attr-defined]

    def _verify_lifecycle_restart(self, receipt: Receipt) -> None:
        outcomes = tuple(getattr(receipt, "lifecycle_outcomes", ()))
        stopped = {getattr(outcome, "pid", None) for outcome in outcomes if getattr(outcome, "client", "") == CLIENT and getattr(outcome, "action", "") == "stop" and getattr(outcome, "status", "") == "stopped"}
        restarted = {getattr(outcome, "pid", None) for outcome in outcomes if getattr(outcome, "client", "") == CLIENT and getattr(outcome, "action", "") == "restart" and getattr(outcome, "status", "") == "restarted"}
        if stopped - restarted:
            raise ValueError("verify_pi_restart_missing")

    def _verify_preserved_package_sentinel(self, settings_path: Path) -> None:
        node_modules = settings_path.parent / "node_modules"
        if not node_modules.exists():
            return
        if not (node_modules / "gentle-pi").is_dir():
            raise ValueError("verify_pi_package_missing")
        bin_dir = node_modules / ".bin"
        if bin_dir.exists() and not (bin_dir / "gentle-pi").exists():
            raise ValueError("verify_pi_binary_missing")


def _settings_paths(context: RuntimeContext) -> tuple[Path, ...]:
    home = context.profile.home
    os_name = context.profile.os_name.lower()
    paths: list[Path] = []
    if os_name == "linux":
        config_home = explicit_platform_config_root(context.profile, "XDG_CONFIG_HOME") or (home / ".config")
        paths.append(config_home / "pi" / "settings.json")
    elif os_name == "macos":
        paths.append(home / "Library" / "Application Support" / "Pi" / "settings.json")
    elif os_name.startswith("win"):
        appdata = explicit_platform_config_root(context.profile, "APPDATA") or (home / "AppData" / "Roaming")
        paths.append(appdata / "Pi" / "settings.json")
    paths.append(home / ".pi" / "settings.json")
    return tuple(dict.fromkeys(path.expanduser() for path in paths))


def _load_settings(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError(f"pi_settings_json_malformed:{path.name}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"pi_settings_invalid_layout:{path.name}")
    packages = data.get("packages", [])
    if packages is None:
        return data
    if not isinstance(packages, list) or not all(isinstance(package, str) for package in packages):
        raise ValueError(f"pi_settings_invalid_packages:{path.name}")
    return data


def _settings_packages(settings: Mapping[str, Any]) -> list[str]:
    packages = settings.get("packages", [])
    if packages is None:
        return []
    if not isinstance(packages, list) or not all(isinstance(package, str) for package in packages):
        raise ValueError("pi_settings_invalid_packages")
    return list(packages)


def _is_active_pi_package(value: str) -> bool:
    return _ACTIVE_PACKAGE_RE.fullmatch(value) is not None


def _settings_candidate(path: Path, active_packages: tuple[str, ...], context: RuntimeContext) -> Candidate:
    root_id, relative_path = root_relative_path(path, context)
    return _candidate(
        rule_id=f"settings:{path}",
        target=path,
        artifact_class=ArtifactClass.ACTIVE_SOURCE,
        ownership=Ownership.PROVEN,
        proposed_action="write_file",
        evidence=({"kind": "pi_package_registration", "packages": active_packages},),
        reason="Pi settings contain active Gentle Pi npm package registration(s)",
        details={
            "kind": "settings_registration",
            "package": active_packages[0],
            "active_packages": active_packages,
            "root_id": root_id,
            "relative_path": relative_path,
        },
    )


def _preserved_package_candidates(settings_dir: Path, context: RuntimeContext) -> tuple[Candidate, ...]:
    candidates: list[Candidate] = []
    package = settings_dir / "node_modules" / "gentle-pi"
    if package.is_dir():
        candidates.append(
            _candidate(
                rule_id=f"preserved-package:{package}",
                target=package,
                artifact_class=ArtifactClass.PRESERVED_INFRASTRUCTURE,
                ownership=Ownership.PRESERVED,
                proposed_action="report_only",
                evidence=({"kind": "installed_npm_package", "package": "gentle-pi"},),
                reason="installed Gentle Pi package infrastructure is preserved",
                details={"kind": "installed_package", "package": "gentle-pi"},
            )
        )
    binary = settings_dir / "node_modules" / ".bin" / "gentle-pi"
    if binary.exists():
        candidates.append(
            _candidate(
                rule_id=f"preserved-binary:{binary}",
                target=binary,
                artifact_class=ArtifactClass.PRESERVED_INFRASTRUCTURE,
                ownership=Ownership.PRESERVED,
                proposed_action="report_only",
                evidence=({"kind": "installed_binary", "binary": "gentle-pi"},),
                reason="Gentle Pi binary shim is package infrastructure and is preserved",
                details={"kind": "installed_binary", "binary": "gentle-pi"},
            )
        )
    return tuple(candidates)


def _cosmetic_candidate(path: Path, context: RuntimeContext) -> Candidate:
    root_id, relative_path = root_relative_path(path, context)
    return _candidate(
        rule_id=f"cosmetic:{path}",
        target=path,
        artifact_class=ArtifactClass.PRESERVED_INFRASTRUCTURE,
        ownership=Ownership.PRESERVED,
        proposed_action="report_only",
        evidence=({"kind": "empty_directory", "path": relative_path},),
        reason="empty .pi/gentle-ai directory is cosmetic in version 1 and is report-only",
        details={"kind": "cosmetic_empty_directory", "root_id": root_id, "relative_path": relative_path},
    )


def _registry_candidate(path: Path, context: RuntimeContext, process_state: _ProcessState) -> Candidate:
    root_id, relative_path = root_relative_path(path, context)
    evidence: list[dict[str, object]] = [{"kind": "exact_project_registry_path", "root_id": root_id, "relative_path": relative_path}]
    details: dict[str, object] = {"kind": "generated_registry", "root_id": root_id, "relative_path": relative_path}
    artifact_class = ArtifactClass.GENERATED_ARTIFACT
    if not path.is_file():
        return _candidate(
            rule_id=f"registry-invalid-layout:{path}",
            target=path,
            artifact_class=ArtifactClass.AMBIGUOUS,
            ownership=Ownership.AMBIGUOUS,
            proposed_action="report_only",
            evidence=tuple(evidence + [{"kind": "invalid_layout"}]),
            reason="project registry path exists but is not a regular file",
            details={**details, "registry_state": "invalid_layout"},
        )
    text = path.read_text(errors="replace")
    if _registry_text_is_proven(text):
        evidence.append({"kind": "generated_registry_signature", "value": REGISTRY_SIGNATURE})
        evidence.append({"kind": "recognized_registry_schema", "schema": "markdown_skill_registry_table"})
        if process_state.block_registry:
            block_reason = process_state.block_reason or "missing_safe_restart_metadata"
            return _candidate(
                rule_id=f"registry-blocked:{path}:{_sha256(text.encode('utf-8', errors='replace'))}",
                target=path,
                artifact_class=artifact_class,
                ownership=Ownership.AMBIGUOUS,
                proposed_action="report_only",
                evidence=tuple(evidence + list(process_state.evidence)),
                reason="Pi process safety is unknown or safe restart metadata is unavailable, so registry mutation is blocked",
                details={**details, "lifecycle_block": block_reason},
            )
        return _candidate(
            rule_id=f"registry:{path}:{_sha256(text.encode('utf-8', errors='replace'))}",
            target=path,
            artifact_class=artifact_class,
            ownership=Ownership.PROVEN,
            proposed_action="delete_file",
            evidence=tuple(evidence),
            reason="project skill registry has the exact Gentle Pi generator signature and recognized markdown registry schema",
            details=details,
        )
    return _candidate(
        rule_id=f"registry-ambiguous:{path}:{_sha256(text.encode('utf-8', errors='replace'))}",
        target=path,
        artifact_class=ArtifactClass.AMBIGUOUS,
        ownership=Ownership.AMBIGUOUS,
        proposed_action="report_only",
        evidence=tuple(evidence),
        reason="project skill registry path exists, but full generator signature and recognized schema were not both present",
        details={**details, "registry_state": "unproven"},
    )


def _attach_lifecycle_to_first_registry(candidates: Sequence[Candidate], process_state: _ProcessState) -> tuple[Candidate, ...]:
    if process_state.lifecycle_action is None:
        return tuple(candidates)
    attached = False
    result: list[Candidate] = []
    for candidate in sorted(candidates, key=lambda item: (item.path, item.candidate_id)):
        if not attached and candidate.ownership == Ownership.PROVEN and candidate.proposed_action != "report_only":
            details = dict(candidate.details)
            details["lifecycle_actions"] = (process_state.lifecycle_action.to_dict(),)
            details["process_evidence"] = process_state.evidence
            candidate = Candidate(
                candidate_id=candidate.candidate_id,
                client=candidate.client,
                path=candidate.path,
                artifact_class=candidate.artifact_class,
                evidence=candidate.evidence,
                ownership=candidate.ownership,
                proposed_action=candidate.proposed_action,
                preimage=candidate.preimage,
                dependencies=candidate.dependencies,
                reason=candidate.reason,
                details=details,
            )
            attached = True
        result.append(candidate)
    return tuple(result)


def _registry_text_is_proven(text: str) -> bool:
    return REGISTRY_SIGNATURE in {line.strip() for line in text.splitlines()} and _registry_has_recognized_schema(text)


def _registry_has_recognized_schema(text: str) -> bool:
    lines = [line.strip() for line in text.splitlines()]
    has_title = any(line in {"# Skill Registry", "# Skills Registry", "## Skill Registry", "## Skills Registry"} for line in lines)
    has_table = False
    normalized = [re.sub(r"\s+", "", line).lower() for line in lines]
    for index, line in enumerate(normalized[:-1]):
        if line in {"|skill|path|", "|name|path|"}:
            separator = normalized[index + 1]
            if separator.startswith("|") and separator.endswith("|") and set(separator) <= {"|", "-", ":"}:
                has_table = True
                break
    return has_title and has_table


def _registry_is_proven(path: Path) -> bool:
    if not path.is_file():
        return False
    return _registry_text_is_proven(path.read_text(errors="replace"))


def _any_proven_registry(context: RuntimeContext) -> bool:
    for root in context.project_roots:
        target = root / ".atl" / "skill-registry.md"
        if _registry_is_proven(target):
            return True
    return False


def _is_authorized_registry_path(path: Path, context: RuntimeContext) -> bool:
    resolved = path.resolve(strict=False)
    for root in context.project_roots:
        target = (root / ".atl" / "skill-registry.md").resolve(strict=False)
        if resolved == target:
            return True
    return False


def _probe_pi_sessions(probe: object, context: RuntimeContext) -> tuple[object, ...]:
    method = getattr(probe, "inspect_pi_processes", None)
    if method is None:
        return ()
    raw = method(context)
    if not isinstance(raw, Sequence) or isinstance(raw, (str, bytes, dict)):
        raise ValueError("pi_process_probe_invalid_result")
    return tuple(raw)


def _session_bool(session: object, key: str) -> bool:
    if isinstance(session, Mapping):
        return bool(session.get(key, False))
    value = getattr(session, key, None)
    if value is not None:
        return bool(value)
    details = getattr(session, "details", {})
    if isinstance(details, Mapping):
        return bool(details.get(key, False))
    return False


def _session_value(session: object, key: str) -> object | None:
    if isinstance(session, Mapping):
        return session.get(key)
    value = getattr(session, key, None)
    if value is not None:
        return value
    details = getattr(session, "details", {})
    if isinstance(details, Mapping):
        return details.get(key)
    return None


def _session_lifecycle_action(session: object, context: RuntimeContext) -> LifecycleAction | None:
    if not _session_bool(session, "restartable"):
        return None
    process_name = _string_value(_session_value(session, "process_name")) or "Pi"
    platform = context.profile.os_name.lower()
    details: dict[str, object] = {"process_name": process_name}
    bundle_id = _string_value(_session_value(session, "bundle_id"))
    restart_argv = _string_sequence(_session_value(session, "restart_argv"))
    if platform == "macos":
        if not bundle_id:
            return None
        details["bundle_id"] = bundle_id
    elif platform == "linux" or platform.startswith("win"):
        if not restart_argv:
            return None
        details["restart_argv"] = restart_argv
    else:
        return None
    pid = _session_value(session, "pid")
    if isinstance(pid, int):
        details["pid"] = pid
    return LifecycleAction(
        client=CLIENT,
        action="stop",
        target=process_name,
        reason="running Pi process loaded Gentle Pi and may regenerate generated skill registries",
        details=details,
    )


def _session_evidence(session: object) -> dict[str, object]:
    evidence: dict[str, object] = {"kind": "pi_process_loaded_gentle_pi", "running": True}
    for key in ("pid", "process_name", "restartable"):
        value = _session_value(session, key)
        if isinstance(value, (str, int, bool)):
            evidence[key] = value
    return evidence


def _string_value(value: object | None) -> str | None:
    return value if isinstance(value, str) and value else None


def _string_sequence(value: object | None) -> tuple[str, ...]:
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)) and all(isinstance(part, str) and part for part in value):
        return tuple(value)
    return ()


def _candidate(
    *,
    rule_id: str,
    target: Path,
    artifact_class: ArtifactClass,
    ownership: Ownership,
    proposed_action: str,
    evidence: Sequence[object],
    reason: str,
    details: Mapping[str, object],
) -> Candidate:
    candidate_key = f"{CLIENT}\0{rule_id}\0{target.resolve(strict=False)}"
    return Candidate(
        candidate_id="sha256:" + hashlib.sha256(candidate_key.encode("utf-8")).hexdigest(),
        client=CLIENT,
        path=str(target),
        artifact_class=artifact_class,
        evidence=tuple(evidence),
        ownership=ownership,
        proposed_action=proposed_action,
        preimage=Preimage(str(target)),
        dependencies=(),
        reason=reason,
        details=dict(details),
    )


def _sha256(content: bytes) -> str:
    return "sha256:" + hashlib.sha256(content).hexdigest()
