from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

from helper.canonical import canonical_bytes
from helper.models import Ownership, RuntimeContext

CATALOG_SCHEMA = "remove-gentle-context.ownership-catalog/v1"
RECEIPT_DIR_ENV_KEYS = (
    "PABLONTIV_SKILLS_RECEIPTS_DIR",
    "SKILLS_RECEIPTS_DIR",
    "SKILLS_RECEIPT_DIR",
)
_MARKER_IDENTIFIER_CHARS = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-/")


@dataclass(frozen=True)
class ExactFileOwnershipDecision:
    ownership: Ownership
    proposed_action: str
    evidence: tuple[dict[str, Any], ...]
    reason: str
    details: dict[str, Any]


def load_ownership_catalog(catalog_path: Path | None = None) -> Mapping[str, Any]:
    skill_root = Path(__file__).resolve().parents[1]
    resolved_catalog_path = catalog_path or skill_root / "references" / "ownership-catalog-v1.json"
    if resolved_catalog_path.exists():
        catalog = json.loads(resolved_catalog_path.read_text())
    else:
        catalog = {
            "schema": CATALOG_SCHEMA,
            "agent_names": [],
            "marker_prefix": "gentle-ai:",
            "generated_registry_signature": "Auto-generated by gentle-pi extensions/skill-registry.ts",
            "canonical_metadata": {"author": "pablontiv"},
            "adapted_skill_provenance": {},
            "personal_skill_releases": {},
        }
    if not isinstance(catalog, dict) or catalog.get("schema") != CATALOG_SCHEMA:
        raise ValueError("ownership_catalog_invalid_schema")
    releases = catalog.get("personal_skill_releases", {})
    if not isinstance(releases, dict):
        raise ValueError("ownership_catalog_invalid_release_map")
    return catalog


def catalog_author(catalog: Mapping[str, Any]) -> str:
    metadata = catalog.get("canonical_metadata", {})
    if isinstance(metadata, dict) and isinstance(metadata.get("author"), str):
        return metadata["author"]
    return "pablontiv"


def classify_exact_file_ownership(
    *,
    target: Path,
    rule_data: Mapping[str, Any],
    default_action: str,
    context: RuntimeContext,
    catalog: Mapping[str, Any],
) -> ExactFileOwnershipDecision:
    content = target.read_bytes()
    digest = "sha256:" + hashlib.sha256(content).hexdigest()
    text = content.decode("utf-8", errors="replace")
    frontmatter = parse_frontmatter(text)
    metadata = frontmatter.get("metadata") if isinstance(frontmatter.get("metadata"), dict) else {}
    evidence: list[dict[str, Any]] = []
    details: dict[str, Any] = {"sha256": digest}

    if metadata.get("author") == catalog_author(catalog):
        details["auto_deletion_veto"] = True
        receipt = verified_personal_receipt(target, digest, frontmatter, metadata, context, catalog)
        if receipt is not None:
            evidence.append({"kind": "verified_installation_receipt", "path": receipt["receipt_path"]})
            details["verified_receipt"] = {k: v for k, v in receipt.items() if k != "receipt_path"}
            return ExactFileOwnershipDecision(
                Ownership.PRESERVED,
                "report_only",
                tuple(evidence),
                "personal ownership verified by metadata, adapted provenance, receipt, trusted release, source commit, content hash, and canonical tree hash",
                details,
            )
        return ExactFileOwnershipDecision(
            Ownership.AMBIGUOUS,
            "report_only",
            tuple(evidence),
            "personal author metadata without complete preservation evidence",
            details,
        )

    corroboration = gentle_corroboration(rule_data, text, digest, catalog)
    if corroboration:
        return ExactFileOwnershipDecision(
            Ownership.PROVEN,
            str(rule_data.get("proposed_action", default_action)),
            tuple(corroboration),
            "Gentle-managed content corroborated by structural marker, generated signature, or fingerprint",
            details,
        )

    return ExactFileOwnershipDecision(
        Ownership.AMBIGUOUS,
        "report_only",
        tuple(evidence),
        "exact path or name alone cannot prove deletion ownership",
        details,
    )


def gentle_corroboration(rule_data: Mapping[str, Any], text: str, digest: str, catalog: Mapping[str, Any]) -> list[dict[str, Any]]:
    evidence: list[dict[str, Any]] = []
    marker_prefix = catalog.get("marker_prefix")
    if isinstance(marker_prefix, str) and marker_prefix:
        evidence.extend(recognized_managed_marker_evidence(text, marker_prefix))
    registry_signature = catalog.get("generated_registry_signature")
    if isinstance(registry_signature, str) and registry_signature in text:
        evidence.append({"kind": "generated_registry_signature", "value": registry_signature})
    for signature in rule_data.get("content_signatures", ()):
        signature_value = signature.get("value")
        if isinstance(signature_value, str) and normalize_digest(signature_value) == digest:
            evidence.append({"kind": "content_signature", "label": signature.get("label", "sha256"), "value": digest})
    return evidence


def recognized_managed_marker_evidence(text: str, marker_prefix: str) -> list[dict[str, str]]:
    evidence: list[dict[str, str]] = []
    seen: set[str] = set()
    for line in text.splitlines():
        identifier = _html_comment_marker_identifier(line.strip(), marker_prefix)
        if identifier is not None and identifier not in seen:
            seen.add(identifier)
            evidence.append({
                "kind": "marker",
                "value": f"<!-- {marker_prefix}{identifier} -->",
                "identifier": identifier,
            })
    return evidence


def _html_comment_marker_identifier(value: str, marker_prefix: str) -> str | None:
    if not value.startswith("<!--") or not value.endswith("-->"):
        return None
    inner = value[len("<!--") : -len("-->")].strip()
    if not inner.startswith(marker_prefix):
        return None
    identifier = inner[len(marker_prefix) :].strip()
    if not identifier:
        return None
    if any(char not in _MARKER_IDENTIFIER_CHARS for char in identifier):
        return None
    return identifier


def parse_frontmatter(text: str) -> dict[str, Any]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    body: list[str] = []
    for line in lines[1:]:
        if line.strip() == "---":
            break
        body.append(line)
    parsed: dict[str, Any] = {}
    current_map: str | None = None
    for line in body:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith((" ", "\t")):
            if current_map is None:
                continue
            key, value = _split_yaml_scalar(line.strip())
            if key is not None:
                nested = parsed.setdefault(current_map, {})
                if isinstance(nested, dict):
                    nested[key] = value
            continue
        key, value = _split_yaml_scalar(line.strip())
        if key is None:
            continue
        if value == "":
            parsed[key] = {}
            current_map = key
        else:
            parsed[key] = value
            current_map = None
    return parsed


def _split_yaml_scalar(line: str) -> tuple[str | None, str]:
    if ":" not in line:
        return None, ""
    key, value = line.split(":", 1)
    key = key.strip()
    value = value.strip()
    if not key:
        return None, ""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        value = value[1:-1]
    return key, value


def verified_personal_receipt(
    target: Path,
    digest: str,
    frontmatter: Mapping[str, Any],
    metadata: Mapping[str, Any],
    context: RuntimeContext,
    catalog: Mapping[str, Any],
) -> dict[str, str] | None:
    skill_name = frontmatter.get("name")
    skill_version = metadata.get("version")
    if not isinstance(skill_name, str) or not isinstance(skill_version, str):
        return None
    if not has_complete_personal_provenance(skill_name, metadata, catalog):
        return None
    release = trusted_personal_release(catalog, skill_name)
    if release is None:
        return None
    actual_tree_sha256 = canonical_tree_sha256(target)
    if actual_tree_sha256 != normalize_digest(release["canonical_tree_sha256"]):
        return None
    for receipt_path in receipt_paths(context):
        try:
            receipt = json.loads(receipt_path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        normalized = normalize_receipt(receipt)
        if normalized is None:
            continue
        if normalized["skill_name"] != skill_name or normalized["skill_version"] != skill_version:
            continue
        if Path(normalized["installed_path"]).expanduser().resolve(strict=False) != target.resolve(strict=False):
            continue
        if normalize_digest(normalized["installed_content_sha256"]) != digest:
            continue
        if normalized["personal_source_repository"] != release["source_repository"]:
            continue
        if normalized["personal_source_commit"] != release["personal_source_commit"]:
            continue
        if normalize_digest(normalized["canonical_tree_sha256"]) != normalize_digest(release["canonical_tree_sha256"]):
            continue
        normalized["canonical_tree_sha256"] = actual_tree_sha256
        normalized["receipt_path"] = str(receipt_path)
        return normalized
    return None


def receipt_paths(context: RuntimeContext) -> tuple[Path, ...]:
    paths: list[Path] = []
    for key in RECEIPT_DIR_ENV_KEYS:
        value = context.profile.env.get(key)
        if value:
            base = Path(value).expanduser()
            if base.is_dir():
                paths.extend(sorted(base.glob("*.json")))
            elif base.is_file():
                paths.append(base)
    return tuple(paths)


def has_complete_personal_provenance(skill_name: str, metadata: Mapping[str, Any], catalog: Mapping[str, Any]) -> bool:
    canonical = catalog.get("canonical_metadata", {})
    if not isinstance(canonical, dict):
        return False
    required = canonical.get("required_string_fields", ["author", "created", "updated", "version"])
    adapted_required = canonical.get(
        "adapted_required_string_fields",
        ["upstream-author", "upstream-repository", "upstream-commit", "ownership"],
    )
    for field in tuple(required) + tuple(adapted_required):
        if not isinstance(metadata.get(field), str) or not metadata.get(field):
            return False
    if metadata.get("author") != canonical.get("author", "pablontiv"):
        return False
    if metadata.get("ownership") != canonical.get("adapted_ownership", "personal"):
        return False
    adapted_provenance = catalog.get("adapted_skill_provenance", {})
    if not isinstance(adapted_provenance, dict):
        return False
    expected = adapted_provenance.get(skill_name)
    if not isinstance(expected, dict):
        return False
    return all(metadata.get(key) == expected.get(key) for key in ("upstream-author", "upstream-repository", "upstream-commit"))


def trusted_personal_release(catalog: Mapping[str, Any], skill_name: str) -> dict[str, str] | None:
    releases = catalog.get("personal_skill_releases", {})
    if not isinstance(releases, dict):
        return None
    release = releases.get(skill_name)
    if not isinstance(release, dict):
        return None
    fields = {
        "source_repository": release.get("source_repository"),
        "personal_source_commit": release.get("personal_source_commit"),
        "canonical_tree_sha256": release.get("canonical_tree_sha256"),
    }
    if not all(isinstance(value, str) and value for value in fields.values()):
        return None
    if not is_full_hex_commit(fields["personal_source_commit"]):
        return None
    if not is_sha256_digest(fields["canonical_tree_sha256"]):
        return None
    return fields


def is_full_hex_commit(value: str) -> bool:
    return len(value) == 40 and all(char in "0123456789abcdef" for char in value)


def canonical_tree_sha256(path: Path) -> str:
    if path.is_file():
        entries = (_canonical_tree_entry(path.name, path),)
    elif path.is_dir():
        root = path
        entries = tuple(
            _canonical_tree_entry(file.relative_to(root).as_posix(), file)
            for file in sorted(candidate for candidate in root.rglob("*") if candidate.is_file())
        )
    else:
        entries = ()
    return "sha256:" + hashlib.sha256(canonical_bytes({"entries": list(entries)})).hexdigest()


def _canonical_tree_entry(relative_path: str, path: Path) -> dict[str, str]:
    digest = "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()
    return {"path": relative_path, "sha256": digest, "type": "file"}


def normalize_receipt(receipt: Any) -> dict[str, str] | None:
    if not isinstance(receipt, dict):
        return None
    skill = receipt.get("skill") if isinstance(receipt.get("skill"), dict) else {}
    fields = {
        "skill_name": receipt.get("skill_name", skill.get("name")),
        "skill_version": receipt.get("skill_version", skill.get("version")),
        "personal_source_repository": receipt.get("personal_source_repository", receipt.get("source_repository")),
        "personal_source_commit": receipt.get("personal_source_commit", receipt.get("source_commit")),
        "installed_path": receipt.get("installed_path"),
        "installed_content_sha256": receipt.get("installed_content_sha256"),
        "installation_timestamp": receipt.get("installation_timestamp", receipt.get("installed_at")),
        "canonical_tree_sha256": receipt.get("canonical_tree_sha256"),
    }
    if not all(isinstance(value, str) and value for value in fields.values()):
        return None
    return dict(fields)


def normalize_digest(value: str) -> str:
    return value if value.startswith("sha256:") else "sha256:" + value


def is_sha256_digest(value: str) -> bool:
    if value.startswith("sha256:"):
        value = value[len("sha256:") :]
    return len(value) == 64 and all(char in "0123456789abcdef" for char in value)
