from __future__ import annotations

import base64
import json
import shutil
import tempfile
import unittest
from pathlib import Path

from helper.clients.claude import ClaudeAdapter
from helper.engine import build_inventory, build_plan
from helper.models import OperationKind, Ownership, PlatformProfile, RuntimeContext
from helper.ownership import canonical_tree_sha256, load_ownership_catalog
from helper.transaction import create_backup, apply_operations
from tests.support import assert_test_home

FIXTURE_ROOT = Path(__file__).resolve().parents[1] / "fixtures" / "claude"


def context_for(home: Path, **env: str) -> RuntimeContext:
    authority_keys = {"XDG_STATE_HOME", "XDG_CONFIG_HOME", "APPDATA", "LOCALAPPDATA"}
    normalized = {key: (str(Path(value).resolve(strict=False)) if key in authority_keys else value) for key, value in env.items()}
    return RuntimeContext(PlatformProfile("linux", home, normalized))


def build_claude_fixture(temp_root: Path) -> Path:
    home = temp_root / "home"
    home.mkdir(parents=True)
    claude = home / ".claude"
    claude.mkdir()
    shutil.copy2(FIXTURE_ROOT / "CLAUDE.md", claude / "CLAUDE.md")
    shutil.copy2(FIXTURE_ROOT / "settings.json", claude / "settings.json")
    themes = claude / "themes"
    themes.mkdir()
    shutil.copy2(FIXTURE_ROOT / "gentleman.json", themes / "gentleman.json")
    return home


class ClaudeAdapterTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.temp_root = Path(self.temp.name)
        self.catalog = load_ownership_catalog()

    def test_finds_theme_and_balanced_blocks(self) -> None:
        home = build_claude_fixture(self.temp_root)
        assert_test_home(home, self.temp_root)

        candidates = ClaudeAdapter(self.catalog).inventory(context_for(home))

        by_path = {Path(c.path).name: c for c in candidates}
        self.assertEqual(by_path["gentleman.json"].ownership, Ownership.PROVEN)
        self.assertTrue(any(c.details.get("marker") == "gentle-ai:sdd-orchestrator" for c in candidates))
        self.assertFalse(any(Path(c.path).name == "skill-registry.md" for c in candidates))

    def test_preserves_usage_counters_engram_marketplace_and_unrelated_skills(self) -> None:
        home = build_claude_fixture(self.temp_root)
        (home / ".claude.json").write_text(json.dumps({"projects": {"/tmp/project": {"history": ["sdd"]}}, "usage": {"sdd": 10}}))
        marketplace = home / ".claude" / "plugins" / "marketplaces" / "engram"
        marketplace.mkdir(parents=True)
        (marketplace / "cache.json").write_text("{}")
        skill = home / ".claude" / "skills" / "model-optimizer"
        skill.mkdir(parents=True)
        (skill / "SKILL.md").write_text("---\nname: model-optimizer\n---\nUnrelated skill.\n")

        candidates = ClaudeAdapter(self.catalog).inventory(context_for(home))

        mutated = {c.path for c in candidates if c.ownership is Ownership.PROVEN}
        self.assertNotIn(str(home / ".claude.json"), mutated)
        self.assertFalse(any("plugins/marketplaces/engram" in path for path in mutated))
        self.assertFalse(any("model-optimizer" in path for path in mutated))

    def test_exact_catalog_agent_deletes_only_with_marker_and_never_atl_registry(self) -> None:
        home = build_claude_fixture(self.temp_root)
        agent = home / ".claude" / "agents" / "sdd-apply.md"
        agent.parent.mkdir(parents=True)
        agent.write_text("# sdd-apply\n\n<!-- gentle-ai:sdd-apply -->\nManaged Claude agent.\n")
        registry = home / ".claude" / ".atl" / "skill-registry.md"
        registry.parent.mkdir(parents=True)
        registry.write_text("Auto-generated by gentle-pi extensions/skill-registry.ts\n<!-- gentle-ai:sdd-apply -->\n")

        inventory = build_inventory(context_for(home), (ClaudeAdapter(self.catalog),))
        plan = build_plan(inventory, context_for(home), (ClaudeAdapter(self.catalog),))

        operation_paths = {operation.path for operation in plan.operations}
        self.assertIn(str(agent), operation_paths)
        self.assertNotIn(str(registry), {candidate.path for candidate in inventory.candidates})
        self.assertTrue(all("/.atl/" not in operation.path for operation in plan.operations))

    def test_compile_removes_balanced_block_byte_exactly_around_block(self) -> None:
        home = build_claude_fixture(self.temp_root)
        source = (home / ".claude" / "CLAUDE.md").read_bytes()
        expected = source.replace(
            b"<!-- gentle-ai:sdd-orchestrator -->\nUse the Gentle SDD orchestrator workflow for specification-driven changes.\nPreserve this managed block exactly unless the removal plan owns it.\n<!-- /gentle-ai:sdd-orchestrator -->\n",
            b"",
        )

        inventory = build_inventory(context_for(home), (ClaudeAdapter(self.catalog),))
        plan = build_plan(inventory, context_for(home), (ClaudeAdapter(self.catalog),))
        write_ops = [op for op in plan.operations if op.path == str(home / ".claude" / "CLAUDE.md")]

        self.assertEqual(len(write_ops), 1)
        self.assertEqual(write_ops[0].kind, OperationKind.WRITE_FILE)
        self.assertEqual(base64.b64decode(write_ops[0].postimage_base64 or ""), expected)

    def test_compile_coalesces_distinct_balanced_blocks_in_one_write(self) -> None:
        home = build_claude_fixture(self.temp_root)
        target = home / ".claude" / "CLAUDE.md"
        source = (
            b"preamble\r\n"
            b"<!-- gentle-ai:sdd-orchestrator -->\n"
            b"managed orchestrator\n"
            b"<!-- /gentle-ai:sdd-orchestrator -->\n"
            b"between\n"
            b"<!-- gentle-ai:sdd-apply -->\n"
            b"managed apply\n"
            b"<!-- /gentle-ai:sdd-apply -->\r\n"
            b"tail-no-newline"
        )
        target.write_bytes(source)
        expected = b"preamble\r\nbetween\ntail-no-newline"

        inventory = build_inventory(context_for(home), (ClaudeAdapter(self.catalog),))
        marker_candidates = [candidate for candidate in inventory.candidates if candidate.path == str(target)]
        self.assertEqual(len(marker_candidates), 2)
        self.assertTrue(all(candidate.ownership is Ownership.PROVEN for candidate in marker_candidates))

        plan = build_plan(inventory, context_for(home), (ClaudeAdapter(self.catalog),))
        write_ops = [operation for operation in plan.operations if operation.path == str(target)]

        self.assertEqual(len(write_ops), 1)
        self.assertEqual(write_ops[0].kind, OperationKind.WRITE_FILE)
        self.assertEqual(base64.b64decode(write_ops[0].postimage_base64 or ""), expected)

    def test_mixed_valid_and_malformed_markers_do_not_remove_any_sibling_block(self) -> None:
        home = build_claude_fixture(self.temp_root)
        target = home / ".claude" / "CLAUDE.md"
        target.write_text(
            "before\n"
            "<!-- gentle-ai:sdd-orchestrator -->\n"
            "managed valid block\n"
            "<!-- /gentle-ai:sdd-orchestrator -->\n"
            "middle\n"
            "<!-- gentle-ai:sdd-apply -->\n"
            "managed but unbalanced\n"
            "after\n"
        )

        inventory = build_inventory(context_for(home), (ClaudeAdapter(self.catalog),))
        marker_candidates = [candidate for candidate in inventory.candidates if candidate.path == str(target)]
        plan = build_plan(inventory, context_for(home), (ClaudeAdapter(self.catalog),))

        self.assertTrue(marker_candidates)
        self.assertTrue(all(candidate.ownership is Ownership.AMBIGUOUS for candidate in marker_candidates))
        self.assertTrue(all(candidate.proposed_action == "report_only" for candidate in marker_candidates))
        self.assertTrue(all(candidate.candidate_id in plan.blocked_candidate_ids for candidate in marker_candidates))
        self.assertFalse(any(operation.path == str(target) for operation in plan.operations))

    def test_malformed_markers_are_ambiguous_report_only(self) -> None:
        cases = {
            "missing_close": "before\n<!-- gentle-ai:sdd-orchestrator -->\nmanaged\n",
            "duplicate_pair": "<!-- gentle-ai:sdd-orchestrator -->\none\n<!-- /gentle-ai:sdd-orchestrator -->\n<!-- gentle-ai:sdd-orchestrator -->\ntwo\n<!-- /gentle-ai:sdd-orchestrator -->\n",
            "nested": "<!-- gentle-ai:sdd-orchestrator -->\nouter\n<!-- gentle-ai:sdd-apply -->\ninner\n<!-- /gentle-ai:sdd-apply -->\n<!-- /gentle-ai:sdd-orchestrator -->\n",
            "unbalanced_close": "before\n<!-- /gentle-ai:sdd-orchestrator -->\nafter\n",
        }
        for name, content in cases.items():
            with self.subTest(name=name):
                case_root = self.temp_root / name
                home = build_claude_fixture(case_root)
                target = home / ".claude" / "CLAUDE.md"
                target.write_text(content)

                inventory = build_inventory(context_for(home), (ClaudeAdapter(self.catalog),))
                marker_candidates = [c for c in inventory.candidates if c.path == str(target)]

                self.assertTrue(marker_candidates)
                self.assertTrue(all(c.ownership is Ownership.AMBIGUOUS for c in marker_candidates))
                self.assertTrue(all(c.proposed_action == "report_only" for c in marker_candidates))
                self.assertIn(marker_candidates[0].candidate_id, build_plan(inventory, context_for(home), (ClaudeAdapter(self.catalog),)).blocked_candidate_ids)

    def test_changed_theme_content_is_ambiguous_report_only(self) -> None:
        home = build_claude_fixture(self.temp_root)
        theme = home / ".claude" / "themes" / "gentleman.json"
        data = json.loads(theme.read_text())
        data["colors"]["accent"] = "#ffffff"
        theme.write_text(json.dumps(data, indent=2) + "\n")

        inventory = build_inventory(context_for(home), (ClaudeAdapter(self.catalog),))
        theme_candidates = [candidate for candidate in inventory.candidates if candidate.path == str(theme)]

        self.assertEqual(len(theme_candidates), 1)
        self.assertEqual(theme_candidates[0].ownership, Ownership.AMBIGUOUS)
        self.assertEqual(theme_candidates[0].proposed_action, "report_only")
        self.assertIn(theme_candidates[0].candidate_id, build_plan(inventory, context_for(home), (ClaudeAdapter(self.catalog),)).blocked_candidate_ids)

    def test_personal_author_metadata_vetoes_auto_delete_and_complete_receipt_preserves(self) -> None:
        home = build_claude_fixture(self.temp_root)
        skill = home / ".claude" / "skills" / "systemic-issue-triage" / "SKILL.md"
        skill.parent.mkdir(parents=True)
        skill.write_text(
            "---\n"
            "name: systemic-issue-triage\n"
            "metadata:\n"
            "  author: pablontiv\n"
            "  created: 2026-01-01\n"
            "  updated: 2026-01-02\n"
            "  version: 1.0.0\n"
            "  upstream-author: Alan-TheGentleman\n"
            "  upstream-repository: https://github.com/Gentleman-Programming/gentle-ai\n"
            "  upstream-commit: d1e1777faafc91a34656ba94bd712972dbe427a1\n"
            "  ownership: personal\n"
            "---\n"
            "Personal adaptation.\n"
        )
        incomplete = ClaudeAdapter(self.catalog).inventory(context_for(home))
        incomplete_skill = [c for c in incomplete if c.path == str(skill)][0]
        self.assertEqual(incomplete_skill.ownership, Ownership.AMBIGUOUS)
        self.assertEqual(incomplete_skill.proposed_action, "report_only")

        release_commit = "a" * 40
        self.assertNotEqual(release_commit, "913bcde")
        release_catalog = dict(self.catalog)
        release_catalog["personal_skill_releases"] = {
            "systemic-issue-triage": {
                "source_repository": "https://github.com/pablontiv/skills",
                "personal_source_commit": release_commit,
                "canonical_tree_sha256": canonical_tree_sha256(skill),
            }
        }
        receipts = self.temp_root / "receipts"
        receipts.mkdir()
        receipt = {
            "skill_name": "systemic-issue-triage",
            "skill_version": "1.0.0",
            "personal_source_repository": "https://github.com/pablontiv/skills",
            "personal_source_commit": release_commit,
            "installed_path": str(skill),
            "installed_content_sha256": "sha256:" + __import__("hashlib").sha256(skill.read_bytes()).hexdigest(),
            "installation_timestamp": "2026-08-19T00:00:00Z",
            "canonical_tree_sha256": canonical_tree_sha256(skill),
        }
        (receipts / "systemic-issue-triage.json").write_text(json.dumps(receipt, sort_keys=True))

        complete = ClaudeAdapter(release_catalog).inventory(context_for(home, SKILLS_RECEIPTS_DIR=str(receipts)))
        complete_skill = [c for c in complete if c.path == str(skill)][0]
        self.assertEqual(complete_skill.ownership, Ownership.PRESERVED)
        self.assertEqual(complete_skill.proposed_action, "report_only")

    def test_second_inventory_plan_after_apply_has_no_claude_mutations(self) -> None:
        home = build_claude_fixture(self.temp_root)
        context = context_for(home, XDG_STATE_HOME=str(self.temp_root / "state"))
        adapter = ClaudeAdapter(self.catalog)
        first_inventory = build_inventory(context, (adapter,))
        first_plan = build_plan(first_inventory, context, (adapter,))
        self.assertTrue(first_plan.operations)

        manifest = create_backup(first_plan, context)
        apply_operations(first_plan, manifest, context)
        second_inventory = build_inventory(context, (ClaudeAdapter(self.catalog),))
        second_plan = build_plan(second_inventory, context, (ClaudeAdapter(self.catalog),))

        self.assertEqual(second_plan.operations, ())
        self.assertFalse(any(candidate.client == "claude" and candidate.ownership is Ownership.PROVEN for candidate in second_inventory.candidates))

    def test_context_project_root_marker_goes_inventory_plan_apply_second_inventory_without_mutation(self) -> None:
        home = build_claude_fixture(self.temp_root)
        project = self.temp_root / "external-project"
        project.mkdir()
        project_claude = project / "CLAUDE.md"
        project_claude_path = str(project_claude.resolve(strict=False))
        project_claude.write_text(
            "Project notes.\n"
            "<!-- gentle-ai:sdd-orchestrator -->\n"
            "Managed project-local instruction.\n"
            "<!-- /gentle-ai:sdd-orchestrator -->\n"
            "Keep this line.\n"
        )
        context = RuntimeContext(PlatformProfile("linux", home, {"XDG_STATE_HOME": str((self.temp_root / "state").resolve(strict=False))}), project_roots=(project,))
        adapter = ClaudeAdapter(self.catalog)

        first_inventory = build_inventory(context, (adapter,))
        project_candidates = [candidate for candidate in first_inventory.candidates if candidate.path == project_claude_path]
        self.assertEqual(len(project_candidates), 1)
        self.assertEqual(project_candidates[0].ownership, Ownership.PROVEN)
        first_plan = build_plan(first_inventory, context, (adapter,))
        project_operations = [operation for operation in first_plan.operations if operation.path == project_claude_path]
        self.assertEqual(len(project_operations), 1)

        manifest = create_backup(first_plan, context)
        apply_operations(first_plan, manifest, context)
        self.assertEqual(project_claude.read_text(), "Project notes.\nKeep this line.\n")

        second_inventory = build_inventory(context, (ClaudeAdapter(self.catalog),))
        second_plan = build_plan(second_inventory, context, (ClaudeAdapter(self.catalog),))

        self.assertFalse(any(candidate.path == project_claude_path and candidate.ownership is Ownership.PROVEN for candidate in second_inventory.candidates))
        self.assertFalse(any(operation.path == project_claude_path for operation in second_plan.operations))

    def test_constructor_project_roots_do_not_create_unbound_project_authority(self) -> None:
        home = build_claude_fixture(self.temp_root)
        project = self.temp_root / "constructor-only-project"
        project.mkdir()
        project_claude = project / "CLAUDE.md"
        project_claude.write_text(
            "<!-- gentle-ai:sdd-orchestrator -->\n"
            "Managed project-local instruction.\n"
            "<!-- /gentle-ai:sdd-orchestrator -->\n"
        )

        inventory = build_inventory(context_for(home), (ClaudeAdapter(self.catalog, project_roots=(project,)),))

        self.assertFalse(any(candidate.path == str(project_claude) for candidate in inventory.candidates))


if __name__ == "__main__":
    unittest.main()
