from __future__ import annotations

import hashlib
import json
import tempfile
import unittest
from pathlib import Path
from typing import Any

from helper.adapter import AdapterRegistry
from helper.declarative import _canonical_tree_sha256, load_declarative_adapter
from helper.models import Ownership, PlatformProfile, RuntimeContext


SKILL_ROOT = Path(__file__).resolve().parents[1]
TEST_SOURCE_COMMIT = "0123456789abcdef0123456789abcdef01234567"
WRONG_SOURCE_COMMIT = "fedcba9876543210fedcba9876543210fedcba98"
SOURCE_REPOSITORY = "https://github.com/pablontiv/skills"
UPSTREAM = {
    "upstream-author": "Alan-TheGentleman",
    "upstream-repository": "https://github.com/Gentleman-Programming/gentle-ai",
    "upstream-commit": "d1e1777faafc91a34656ba94bd712972dbe427a1",
}


class DeclarativeAdapterTests(unittest.TestCase):
    def test_adapter_registry_rejects_duplicate_and_unknown_clients(self):
        class StubAdapter:
            client = "gemini"

            def inventory(self, context):
                return ()

            def compile(self, candidate, context):
                return ()

            def verify(self, receipt, context):
                return ()

        registry = AdapterRegistry()
        adapter = StubAdapter()
        registry.register(adapter)
        self.assertIs(registry.for_client("gemini"), adapter)
        with self.assertRaisesRegex(ValueError, "adapter_duplicate_client"):
            registry.register(StubAdapter())
        with self.assertRaisesRegex(ValueError, "adapter_unknown_client"):
            registry.for_client("unknown")

    def _context(self, home: Path, **env: str) -> RuntimeContext:
        return RuntimeContext(PlatformProfile("linux", home, dict(env)))

    def _write_exact_file_adapter(self, path: Path) -> None:
        path.write_text(json.dumps({
            "schema": "remove-gentle-context.adapter/v1",
            "client": "gemini",
            "roots": {"config": {"kind": "home_relative", "path": ".gemini"}},
            "rules": [{"id": "adapted", "kind": "exact_file", "root": "config", "path": "agents/systemic-issue-triage.md"}],
        }))

    def _personal_content(
        self,
        *,
        author: str = "pablontiv",
        include_adapted_metadata: bool = True,
    ) -> str:
        adapted = ""
        if include_adapted_metadata:
            adapted = """  upstream-author: "Alan-TheGentleman"
  upstream-repository: "https://github.com/Gentleman-Programming/gentle-ai"
  upstream-commit: "d1e1777faafc91a34656ba94bd712972dbe427a1"
  ownership: "personal"
"""
        return f"""---
name: systemic-issue-triage
metadata:
  author: "{author}"
  created: "2026-08-19"
  updated: "2026-08-19"
  version: "0.1.0"
{adapted}---
# Personal adaptation
"""

    def _catalog(
        self,
        *,
        source_commit: str,
        canonical_tree_sha256: str,
        include_release: bool = True,
        include_adapted_provenance: bool = True,
    ) -> dict[str, Any]:
        catalog: dict[str, Any] = {
            "schema": "remove-gentle-context.ownership-catalog/v1",
            "agent_names": [],
            "marker_prefix": "gentle-ai:",
            "generated_registry_signature": "Auto-generated by gentle-pi extensions/skill-registry.ts",
            "ownership_authority": {
                "issue": "https://github.com/pablontiv/skills/issues/1",
                "adr_path": "docs/adr/0001-portable-skill-ownership-and-provenance.md",
                "authority_commit": "913bcde",
            },
            "canonical_metadata": {
                "required_string_fields": ["author", "created", "updated", "version"],
                "author": "pablontiv",
                "adapted_required_string_fields": ["upstream-author", "upstream-repository", "upstream-commit", "ownership"],
                "adapted_ownership": "personal",
            },
            "personal_skill_releases": {},
        }
        if include_adapted_provenance:
            catalog["adapted_skill_provenance"] = {"systemic-issue-triage": dict(UPSTREAM, license="Apache-2.0")}
        if include_release:
            catalog["personal_skill_releases"] = {
                "systemic-issue-triage": {
                    "source_repository": SOURCE_REPOSITORY,
                    "personal_source_commit": source_commit,
                    "canonical_tree_sha256": canonical_tree_sha256,
                }
            }
        return catalog

    def _receipt(
        self,
        *,
        target: Path,
        content_sha256: str,
        canonical_tree_sha256: str,
        source_commit: str = TEST_SOURCE_COMMIT,
    ) -> dict[str, str]:
        return {
            "skill_name": "systemic-issue-triage",
            "skill_version": "0.1.0",
            "personal_source_repository": SOURCE_REPOSITORY,
            "personal_source_commit": source_commit,
            "installed_path": str(target),
            "installed_content_sha256": content_sha256,
            "installation_timestamp": "2026-08-19T00:00:00Z",
            "canonical_tree_sha256": canonical_tree_sha256,
        }

    def test_loads_exact_file_and_json_array_rules(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "adapter.json"
            path.write_text(json.dumps({
                "schema": "remove-gentle-context.adapter/v1",
                "client": "gemini",
                "roots": {"config": {"kind": "home_relative", "path": ".gemini"}},
                "rules": [
                    {"id": "agent", "kind": "exact_file", "root": "config", "path": "agents/sdd-init.md"},
                    {"id": "hook", "kind": "json_array_value", "root": "config", "path": "settings.json", "pointer": "/hooks", "value": "gentle-hook"},
                ],
            }))
            adapter = load_declarative_adapter(path)
            self.assertEqual(adapter.client, "gemini")
            self.assertEqual(len(adapter.rules), 2)

    def test_fixture_files_cover_valid_and_forbidden_declarative_examples(self):
        fixture_root = SKILL_ROOT / "tests" / "fixtures" / "declarative"
        self.assertEqual(load_declarative_adapter(fixture_root / "valid.json").client, "gemini")
        with self.assertRaisesRegex(ValueError, "adapter_forbidden_capability"):
            load_declarative_adapter(fixture_root / "forbidden-toml.json")

    def test_rejects_toml_sqlite_runtime_and_arbitrary_text_rules(self):
        forbidden = ["toml_edit", "sqlite_update", "runtime_state", "regex_replace"]
        for kind in forbidden:
            with self.subTest(kind=kind), tempfile.TemporaryDirectory() as td:
                path = Path(td) / "adapter.json"
                path.write_text(json.dumps({
                    "schema": "remove-gentle-context.adapter/v1",
                    "client": "bad",
                    "roots": {"config": {"kind": "home_relative", "path": ".bad"}},
                    "rules": [{"id": "bad", "kind": kind, "root": "config", "path": "state"}],
                }))
                with self.assertRaisesRegex(ValueError, "adapter_forbidden_capability"):
                    load_declarative_adapter(path)

    def test_shipped_catalog_records_adr_authority_but_no_personal_release(self):
        catalog = json.loads((SKILL_ROOT / "references" / "ownership-catalog-v1.json").read_text())
        self.assertEqual(catalog["ownership_authority"]["authority_commit"], "913bcde")
        self.assertEqual(catalog["ownership_authority"]["adr_path"], "docs/adr/0001-portable-skill-ownership-and-provenance.md")
        self.assertEqual(catalog["ownership_authority"]["issue"], "https://github.com/pablontiv/skills/issues/1")
        self.assertEqual(catalog["personal_skill_releases"], {})
        self.assertNotIn("personal_source_commit", catalog)
        self.assertNotIn("canonical_tree_sha256", catalog)
        self.assertNotIn("personal_source_commit=913bcde", catalog["preserved_requires"])

    def test_loads_every_shipped_adapter_with_unique_clients_and_rule_ids(self):
        forbidden = ("toml_edit", "sqlite_update", "runtime_state", "regex_replace")
        seen_clients: set[str] = set()
        for path in sorted((SKILL_ROOT / "adapters").glob("*.json")):
            with self.subTest(adapter=path.name):
                serialized = path.read_text()
                for token in forbidden:
                    self.assertNotIn(token, serialized)
                adapter = load_declarative_adapter(path)
                self.assertNotIn(adapter.client, seen_clients)
                seen_clients.add(adapter.client)
                rule_ids = [rule.id for rule in adapter.rules]
                self.assertEqual(len(rule_ids), len(set(rule_ids)))
        self.assertEqual(seen_clients, {"gemini", "kimi", "hermes", "vscode-copilot"})

    def test_byte_identical_gentle_asset_is_not_preserved(self):
        content = "---\nname: sdd-init\n---\n# Gentle upstream asset\n"
        digest = "sha256:" + hashlib.sha256(content.encode()).hexdigest()
        with tempfile.TemporaryDirectory() as td:
            home = Path(td) / "home"
            target = home / ".gemini" / "agents" / "sdd-init.md"
            target.parent.mkdir(parents=True)
            target.write_text(content)
            adapter_path = Path(td) / "adapter.json"
            adapter_path.write_text(json.dumps({
                "schema": "remove-gentle-context.adapter/v1",
                "client": "gemini",
                "roots": {"config": {"kind": "home_relative", "path": ".gemini"}},
                "rules": [{
                    "id": "sdd-init",
                    "kind": "exact_file",
                    "root": "config",
                    "path": "agents/sdd-init.md",
                    "content_signatures": [{"algorithm": "sha256", "value": digest, "label": "gentle-byte-identical"}],
                }],
            }))
            (candidate,) = load_declarative_adapter(adapter_path).inventory(self._context(home))
            self.assertEqual(candidate.ownership, Ownership.PROVEN)
            self.assertEqual(candidate.proposed_action, "delete_file")
            self.assertNotEqual(candidate.ownership, Ownership.PRESERVED)

    def test_author_only_personal_adaptation_is_ambiguous_and_vetoes_delete(self):
        content = """---
name: systemic-issue-triage
metadata:
  author: "pablontiv"
  created: "2026-08-19"
  updated: "2026-08-19"
  version: "0.1.0"
---
# Adapted skill without receipt
"""
        with tempfile.TemporaryDirectory() as td:
            home = Path(td) / "home"
            target = home / ".gemini" / "agents" / "systemic-issue-triage.md"
            target.parent.mkdir(parents=True)
            target.write_text(content)
            adapter_path = Path(td) / "adapter.json"
            self._write_exact_file_adapter(adapter_path)
            (candidate,) = load_declarative_adapter(adapter_path).inventory(self._context(home))
            self.assertEqual(candidate.ownership, Ownership.AMBIGUOUS)
            self.assertEqual(candidate.proposed_action, "report_only")
            self.assertTrue(candidate.details["auto_deletion_veto"])

    def test_temp_catalog_release_receipt_and_installed_tree_preserve_personal_adaptation(self):
        content = self._personal_content()
        with tempfile.TemporaryDirectory() as td:
            home = Path(td) / "home"
            receipts = Path(td) / "receipts"
            receipts.mkdir()
            target = home / ".gemini" / "agents" / "systemic-issue-triage.md"
            target.parent.mkdir(parents=True)
            target.write_text(content)
            content_digest = "sha256:" + hashlib.sha256(content.encode()).hexdigest()
            tree_digest = _canonical_tree_sha256(target)
            (receipts / "systemic-issue-triage.json").write_text(json.dumps(self._receipt(
                target=target,
                content_sha256=content_digest,
                canonical_tree_sha256=tree_digest,
            )))
            catalog_path = Path(td) / "ownership-catalog-v1.json"
            catalog_path.write_text(json.dumps(self._catalog(
                source_commit=TEST_SOURCE_COMMIT,
                canonical_tree_sha256=tree_digest,
            )))
            adapter_path = Path(td) / "adapter.json"
            self._write_exact_file_adapter(adapter_path)
            (candidate,) = load_declarative_adapter(adapter_path, catalog_path=catalog_path).inventory(
                self._context(home, PABLONTIV_SKILLS_RECEIPTS_DIR=str(receipts))
            )
            self.assertEqual(candidate.ownership, Ownership.PRESERVED)
            self.assertEqual(candidate.proposed_action, "report_only")
            self.assertEqual(candidate.details["verified_receipt"]["personal_source_commit"], TEST_SOURCE_COMMIT)
            self.assertEqual(candidate.details["verified_receipt"]["canonical_tree_sha256"], tree_digest)
            self.assertNotEqual(candidate.details["verified_receipt"]["personal_source_commit"], "913bcde")

    def test_preserved_requires_every_personal_release_conjunct(self):
        cases = (
            "missing_release",
            "missing_adapted_provenance",
            "adr_authority_commit_in_receipt",
            "wrong_full_source_commit_in_receipt",
            "wrong_receipt_tree_sha256",
            "wrong_release_tree_sha256",
            "wrong_receipt_content_sha256",
            "actual_installed_content_drift",
            "author_not_pablontiv",
            "missing_adapted_metadata",
        )
        for case in cases:
            with self.subTest(case=case), tempfile.TemporaryDirectory() as td:
                home = Path(td) / "home"
                receipts = Path(td) / "receipts"
                receipts.mkdir()
                target = home / ".gemini" / "agents" / "systemic-issue-triage.md"
                target.parent.mkdir(parents=True)
                content = self._personal_content(
                    author="someone-else" if case == "author_not_pablontiv" else "pablontiv",
                    include_adapted_metadata=case != "missing_adapted_metadata",
                )
                target.write_text(content)
                content_digest = "sha256:" + hashlib.sha256(content.encode()).hexdigest()
                tree_digest = _canonical_tree_sha256(target)
                catalog_tree = "sha256:" + "1" * 64 if case == "wrong_release_tree_sha256" else tree_digest
                receipt_tree = "sha256:" + "2" * 64 if case == "wrong_receipt_tree_sha256" else tree_digest
                receipt_content = "sha256:" + "3" * 64 if case == "wrong_receipt_content_sha256" else content_digest
                receipt_commit = {
                    "adr_authority_commit_in_receipt": "913bcde",
                    "wrong_full_source_commit_in_receipt": WRONG_SOURCE_COMMIT,
                }.get(case, TEST_SOURCE_COMMIT)
                catalog = self._catalog(
                    source_commit=TEST_SOURCE_COMMIT,
                    canonical_tree_sha256=catalog_tree,
                    include_release=case != "missing_release",
                    include_adapted_provenance=case != "missing_adapted_provenance",
                )
                catalog_path = Path(td) / "ownership-catalog-v1.json"
                catalog_path.write_text(json.dumps(catalog))
                (receipts / "systemic-issue-triage.json").write_text(json.dumps(self._receipt(
                    target=target,
                    content_sha256=receipt_content,
                    canonical_tree_sha256=receipt_tree,
                    source_commit=receipt_commit,
                )))
                if case == "actual_installed_content_drift":
                    target.write_text(content + "\nchanged after receipt\n")
                adapter_path = Path(td) / "adapter.json"
                self._write_exact_file_adapter(adapter_path)
                (candidate,) = load_declarative_adapter(adapter_path, catalog_path=catalog_path).inventory(
                    self._context(home, PABLONTIV_SKILLS_RECEIPTS_DIR=str(receipts))
                )
                self.assertEqual(candidate.ownership, Ownership.AMBIGUOUS)
                self.assertEqual(candidate.proposed_action, "report_only")
                if case != "author_not_pablontiv":
                    self.assertTrue(candidate.details["auto_deletion_veto"])


if __name__ == "__main__":
    unittest.main()
