from __future__ import annotations

import hashlib
import tempfile
import unittest
from pathlib import Path

from helper.models import Ownership, PlatformProfile, RuntimeContext
from helper.ownership import classify_exact_file_ownership, recognized_managed_marker_evidence


class OwnershipTests(unittest.TestCase):
    def _context(self, home: Path) -> RuntimeContext:
        return RuntimeContext(PlatformProfile("linux", home, {}))

    def test_managed_marker_requires_complete_trimmed_html_comment_with_identifier(self):
        text = "\n".join((
            "A prose note mentions gentle-ai:sdd-init.",
            "https://example.invalid/?q=gentle-ai:sdd-init",
            "`gentle-ai:sdd-init`",
            "<!-- docs mention gentle-ai:sdd-init, not a managed marker -->",
            "<!-- gentle-ai: -->",
            "  <!-- gentle-ai:sdd-init -->  ",
        ))
        self.assertEqual(
            recognized_managed_marker_evidence(text, "gentle-ai:"),
            [{"kind": "marker", "value": "<!-- gentle-ai:sdd-init -->", "identifier": "sdd-init"}],
        )

    def test_exact_file_corroboration_accepts_signature_and_content_digest(self):
        with tempfile.TemporaryDirectory() as td:
            home = Path(td) / "home"
            home.mkdir()
            target = home / "asset.md"
            content = "Auto-generated by gentle-pi extensions/skill-registry.ts\n"
            target.write_text(content)
            digest = "sha256:" + hashlib.sha256(content.encode()).hexdigest()
            raw_digest = digest.removeprefix("sha256:")
            decision = classify_exact_file_ownership(
                target=target,
                rule_data={"content_signatures": [{"algorithm": "sha256", "value": raw_digest, "label": "exact"}]},
                default_action="delete_file",
                context=self._context(home),
                catalog={
                    "marker_prefix": "gentle-ai:",
                    "generated_registry_signature": "Auto-generated by gentle-pi extensions/skill-registry.ts",
                    "canonical_metadata": {"author": "pablontiv"},
                    "personal_skill_releases": {},
                },
            )
            self.assertEqual(decision.ownership, Ownership.PROVEN)
            self.assertEqual({item["kind"] for item in decision.evidence}, {"generated_registry_signature", "content_signature"})

    def test_unsupported_yaml_metadata_structure_fails_closed(self):
        with tempfile.TemporaryDirectory() as td:
            home = Path(td) / "home"
            home.mkdir()
            target = home / "skill.md"
            target.write_text("---\nname: bad\nmetadata: {author: pablontiv}\n---\n")
            decision = classify_exact_file_ownership(
                target=target,
                rule_data={},
                default_action="delete_file",
                context=self._context(home),
                catalog={"marker_prefix": "gentle-ai:", "canonical_metadata": {"author": "pablontiv"}, "personal_skill_releases": {}},
            )
            self.assertEqual(decision.ownership, Ownership.AMBIGUOUS)
            self.assertEqual(decision.proposed_action, "report_only")
            self.assertNotIn("auto_deletion_veto", decision.details)


if __name__ == "__main__":
    unittest.main()
